### ISSUE TITLE
Special case: Missing Tracking

### ISSUE THREAD

**Issue by NguyenMinhh** [hoadinh2010/Vietexpress#122]
- [x] In case tracking was found in US, handle as new tracking number, move it to new flight and remove from the old one.

- [ ] In case tracking was found in VN, add this tracking to Receipt( * ) which will be re-sent to customer and change its status to 'VN Delivered' from that Flight.
( * )Receipt can be sent multiple time. When creating a Receipt, missing tracking must not be added automatically. Staff must add missing tracking once the missing tracking was found in Vietnam, and re-calculate shipping fee, etc...

- [x] In case tracking was not found, do nothing.
