### ISSUE TITLE
Improve tracking list of a flight view

### ISSUE THREAD

**Issue by nguyenhuuhoanggiang** [hoadinh2010/Vietexpress#157]
- [x] Add "Người gửi" Column
- [x] Change "Khách hàng" Column name to "Người nhận"
- [x] Add "Số kiện" Column
- [x] Add "Trọng lượng" Column
- [x] Add "Phí ship" Column
- [x] Add "Nội dung" Column
- Group by Customer Id
- "Quà biếu" must be listed at the end of table
