### ISSUE TITLE
Complete the Tracking creation form 

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#39]
- [x] Get customer list to the `Khach hang` dropdown
- [x] Add `Chưa xác định` option to the list customers
- [x] Submit from when keydown
- [x] Show list tracking below the creation form
- [x] Have a delete button to delete tracking
