### ISSUE TITLE
Enhance the detail tracking Page 

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#79]
- [x] Using the value instead of enum data![image](https://user-images.githubusercontent.com/48083610/54824944-eb8f5280-4cde-11e9-8fa7-82d1d6874c8c.png)
- [x] If this tracking is not belonged to anyone, show a tag in the `thông tin khách hàng` that says  `Chưa xác định`, Remove all information in this section. In the position of `Chọn khách hàng`, use the Khách hàng dropdown like the adding tracking form. This dropdown doesn't need label, just have place holder `Chọn khách hàng`
- [x] If this tracking have already belonged to a customer, don't need to show the khach hang dropdown.

**Comment by tichondrius** [comment]
``
