### ISSUE TITLE
Add more fields to show more detail about a flight and change the status of flight and tracking 

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#82]
- [x] When finish adding tracking to flight, change the status of flight to `ON_BOARD` (already done), and change all trackings in this flight to `ON_BOARD`, too. 
- [ ] Add new status of tracking: `MISSING: Thất lạc`. A tracking will be changed to this status after checking flight process and can't find this tracking. Most of time, this status will be changed from `ON_BOARD`
- [x] Add field `Trackings` to the schema of the flights. This is a object:
`
trackings: {
  total: Number
  checked: Number
  missing: Number,
  add: Number
}
`
- [x] `total` will be updated when finish adding tracking to flight, total tracking of the flight
- [ ] `checked` will be updated when finish checking flight. This is the total number of the tracking which are checked after checking flight (tracking status = VN_DELIVERIED)
- [ ] `missing` will be udpated when finish checking flight. This is the total trackings which are status `MISSING ` in this flight 
- [ ] `add` will be updated when finish checking flight. This is the total trackings which are not in this flight on our DB but when check in realtime, we have it on the flight
