### ISSUE TITLE
Show the tracking statistic number of a flight 

### ISSUE THREAD

**Issue by hoadinh2010** [hoadinh2010/Vietexpress#83]
- [x] In the flight list have a new column `Tình trạng vận đơn` will be shown :`/total/checked/missing/add` (Example: 150 / 149 / 1 / 5). Those are the number of tracking. The data is get form the `trackings` property of the flight.
- [x] When hover on the string, show the tooltip, using  popover component of ant design, should have the color for each kind of number (Red for missing, total is normal, green for checked, Blue for add):
`
Tổng số vận đơn: 150
Vận đơn đã kiểm tra: 149
Vận đơn thất lạc: 1
Vận đơn dư: 5
`
![image](https://user-images.githubusercontent.com/48083610/54829010-1336e880-4ce8-11e9-90a3-a90253ff9442.png)
- [x] In the flight detail page, add more information like the above
