### ISSUE TITLE
Change tracking number's owner when scanning bar code

### ISSUE THREAD

**Issue by nguyenhuuhoanggiang** [hoadinh2010/Vietexpress#97]
**Allow re-scan existed tracking:**
- [ ] Choose new customer Id before scanning again the existed tracking number.
- [ ] Overwrite tracking number and new customer Id, show message.
- [ ] Overwrite tracking number and not show message in case customer Id has not been changed!

**Comment by hoadinh2010** [comment]
@NguyenMinhh  Check a special case: when adding tracking to flight, if the input tracking is existed in the system and status === 'Missing', still add this tracking to the flight and change the status of this tracking like another new tracking

**Comment by nguyenhuuhoanggiang** [comment]
1. In case tracking was found in US, handle as new tracking number, move it to new flight and remove from the old one. 

2. In case tracking was found in VN, add this tracking to Receipt( * ) which will be re-sent to customer and change its status to 'VN Delivered' from that Flight.
( * )Receipt can be sent multiple time. When creating a Receipt, missing tracking must not be added automatically. Staff must add missing tracking once the missing tracking was found in Vietnam, and re-calculate shipping fee, etc...  

3. In case tracking was not found, do nothing.
